AWSTemplateFormatVersion: 2010-09-09
Description: Create the VPC for the Tournament Application

Resources:
    TournamentVPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.0.0/16
            EnableDnsHostnames: true
            Tags:
                - Key: Name
                  Value: TournamentVPC
    TournamentIG:
        Type: AWS::EC2::InternetGateway
        Properties:
            Tags:
                - Key: Name
                  Value: TournamentVPC Internet Gateway
    TournamentVPCAttachIG:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            VpcId: !Ref TournamentVPC
            InternetGatewayId: !Ref TournamentIG
    TournamentPublicSubnet1:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref TournamentVPC
            CidrBlock: 10.0.0.0/24
            AvailabilityZone: !Select
             - '0'
             - !GetAZs ''
            Tags:
                - Key: Name
                  Value: Tournament Public Subnet 1
    TournamentPublicSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref TournamentVPC
            CidrBlock: 10.0.1.0/24
            AvailabilityZone: !Select
             - '1'
             - !GetAZs ''
            Tags:
                - Key: Name
                  Value: Tournament Public Subnet 2
    TournamentPublicSubnet3:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref TournamentVPC
            CidrBlock: 10.0.2.0/24
            AvailabilityZone: !Select
             - '2'
             - !GetAZs ''
            Tags:
                - Key: Name
                  Value: Tournament Public Subnet 3
    TournamentPrivateSubnet1:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref TournamentVPC
            CidrBlock: 10.0.64.0/18
            AvailabilityZone: !Select
             - '0'
             - !GetAZs ''
            Tags:
                - Key: Name
                  Value: Tournament Private Subnet 1
    TournamentPrivateSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref TournamentVPC
            CidrBlock: 10.0.128.0/18
            AvailabilityZone: !Select
             - '1'
             - !GetAZs ''
            Tags:
                - Key: Name
                  Value: Tournament Private Subnet 2
    TournamentPrivateSubnet3:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref TournamentVPC
            CidrBlock: 10.0.192.0/18
            AvailabilityZone: !Select
             - '2'
             - !GetAZs ''
            Tags:
                - Key: Name
                  Value: Tournament Private Subnet 3
    TournamentPublicRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref TournamentVPC
            Tags:
                - Key: Name
                  Value: Tournament Public Route Table
    TournamentPublicRoute:
        Type: AWS::EC2::Route
        Properties:
            RouteTableId: !Ref TournamentPublicRouteTable
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref TournamentIG
    TournamentPublicSubnetRouteTableAssociation1:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            SubnetId: !Ref TournamentPublicSubnet1
            RouteTableId: !Ref TournamentPublicRouteTable
    TournamentPublicSubnetRouteTableAssociation2:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            SubnetId: !Ref TournamentPublicSubnet2
            RouteTableId: !Ref TournamentPublicRouteTable
    TournamentPublicSubnetRouteTableAssociation3:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            SubnetId: !Ref TournamentPublicSubnet3
            RouteTableId: !Ref TournamentPublicRouteTable
    TournamentPrivateRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref TournamentVPC
            Tags:
                - Key: Name
                  Value: Tournament Private Route Table
    TournamentPrivateSubnetRouteTableAssociation1:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            SubnetId: !Ref TournamentPrivateSubnet1
            RouteTableId: !Ref TournamentPrivateRouteTable
    TournamentPrivateSubnetRouteTableAssociation2:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            SubnetId: !Ref TournamentPrivateSubnet2
            RouteTableId: !Ref TournamentPrivateRouteTable
    TournamentPrivateSubnetRouteTableAssociation3:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            SubnetId: !Ref TournamentPrivateSubnet3
            RouteTableId: !Ref TournamentPrivateRouteTable
    TournamentInternalSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Default Admin Security Group
            GroupName: Default Admin Security Group
            VpcId: !Ref TournamentVPC
    TournamentAdminSecurityGroupAllowAllSelf:
        Type: AWS::EC2::SecurityGroupIngress
        Properties:
            GroupId: !Ref TournamentInternalSecurityGroup
            IpProtocol: '-1'
            SourceSecurityGroupId: !Ref TournamentInternalSecurityGroup
    TournamentAdminSecurityGroupAllowIn:
        Type: AWS::EC2::SecurityGroupIngress
        Properties:
            GroupId: !Ref TournamentInternalSecurityGroup
            CidrIp: 0.0.0.0/0
            IpProtocol: -1
            FromPort: -1
            ToPort: -1
    TournamentAdminSecurityGroupAllOut:
        Type: AWS::EC2::SecurityGroupEgress
        Properties:
            GroupId: !Ref TournamentInternalSecurityGroup
            CidrIp: 0.0.0.0/0
            IpProtocol: -1
            FromPort: -1
            ToPort: -1
    TournamentCloudwatchLogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: /tournament/
            RetentionInDays: 14
    TournamentVpcDhcpOptions:
        Type: AWS::EC2::DHCPOptions
        Properties:
            DomainName: shiftedhelix.com
            DomainNameServers:
                - AmazonProvidedDNS
            Tags:
                - Key: Name
                  Value: Tournament DHCP Option Set
    TournamentVpcDhcpOptionAssociation:
        Type: AWS::EC2::VPCDHCPOptionsAssociation
        Properties:
            DhcpOptionsId: !Ref TournamentVpcDhcpOptions
            VpcId: !Ref TournamentVPC
    TournamentNetworkAcl:
        Type: AWS::EC2::NetworkAcl
        Properties:
            VpcId: !Ref TournamentVPC
            Tags:
                - Key: Name
                  Value: Tournament ACL
    TournamentInboundAclEntry:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            NetworkAclId: !Ref TournamentNetworkAcl
            RuleNumber: 100
            Protocol: -1
            RuleAction: allow
            CidrBlock: 0.0.0.0/0
    TournamentOutboundAclEntry:
        Type: AWS::EC2::NetworkAclEntry
        Properties:
            NetworkAclId: !Ref TournamentNetworkAcl
            RuleNumber: 100
            Protocol: -1
            RuleAction: allow
            CidrBlock: 0.0.0.0/0
            Egress: true
    TournamentPublicSubnet1AclAssociation:
        Type: AWS::EC2::SubnetNetworkAclAssociation
        Properties:
            NetworkAclId: !Ref TournamentNetworkAcl
            SubnetId: !Ref TournamentPublicSubnet1
    TournamentPublicSubnet2AclAssociation:
        Type: AWS::EC2::SubnetNetworkAclAssociation
        Properties:
            NetworkAclId: !Ref TournamentNetworkAcl
            SubnetId: !Ref TournamentPublicSubnet2
    TournamentPublicSubnet3AclAssociation:
        Type: AWS::EC2::SubnetNetworkAclAssociation
        Properties:
            NetworkAclId: !Ref TournamentNetworkAcl
            SubnetId: !Ref TournamentPublicSubnet3
    TournamentPrivateSubnet1AclAssociation:
        Type: AWS::EC2::SubnetNetworkAclAssociation
        Properties:
            NetworkAclId: !Ref TournamentNetworkAcl
            SubnetId: !Ref TournamentPrivateSubnet1
    TournamentPrivateSubnet2AclAssociation:
        Type: AWS::EC2::SubnetNetworkAclAssociation
        Properties:
            NetworkAclId: !Ref TournamentNetworkAcl
            SubnetId: !Ref TournamentPrivateSubnet2
    TournamentPrivateSubnet3AclAssociation:
        Type: AWS::EC2::SubnetNetworkAclAssociation
        Properties:
            NetworkAclId: !Ref TournamentNetworkAcl
            SubnetId: !Ref TournamentPrivateSubnet3
    